#!/usr/bin/env python3
"""
Orbis Local Live PDF Aggregator
Reads the intermediate JSON files generated by the dashboard steps
and uses them to generate a live PDF report.
"""
import json
import os
import sys

# Add OpenAI and Dotenv for enrichment
try:
    import openai
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Import the existing PDF generator function
try:
    from generate_pdf_report import generate_report
except ImportError:
    print("ERROR: generate_pdf_report.py not found in the same directory.")
    sys.exit(1)

def enrich_findings_with_ai(findings, brand_name, url):
    """Use OpenAI to expand brief findings into detailed reports with examples."""
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key or not findings:
        return findings

    try:
        from openai import OpenAI
        client = OpenAI(api_key=api_key)
        model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")

        prompt = f"""You are a GEO (Generative Engine Optimization) expert.
I have a list of findings for the brand "{brand_name}" and URL "{url}".
For each finding, I need you to:
1. Keep the title.
2. Provide a 'detailed_description' (2-3 sentences explaining exactly what is wrong).
3. Provide an 'impact' statement (how this specifically hurts their visibility in AI search like ChatGPT/Perplexity).
4. Provide a 'fix_example' (a concrete example of what a fix looks like, e.g. a code snippet, a robots.txt rule, or a schema example).

Current Findings:
{json.dumps(findings, indent=2)}

Return the results as a JSON list of objects, each having:
"severity", "title", "detailed_description", "impact", "fix_example"
"""

        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"}
        )
        
        enriched_data = json.loads(response.choices[0].message.content)
        # Handle if the AI wraps it in a "findings" key or just returns a list
        if isinstance(enriched_data, dict) and "findings" in enriched_data:
            return enriched_data["findings"]
        elif isinstance(enriched_data, list):
            return enriched_data
        return findings

    except Exception as e:
        print(f"Error enriching findings: {e}")
        return findings

def generate_optimization_roadmap(data):
    """Use AI to generate a prioritized optimization roadmap based on audit data."""
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        return {"quick_wins": [], "medium_term": [], "strategic": []}

    try:
        from openai import OpenAI
        client = OpenAI(api_key=api_key)
        model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")

        # Prepare a summary of the current status for the AI
        status_summary = {
            "brand": data.get("brand_name"),
            "url": data.get("url"),
            "scores": data.get("scores"),
            "top_findings": [f.get("title") for f in data.get("findings", [])[:5]],
            "has_gbp": data.get("gbp") is not None,
            "visibility": {
                "avg_rank": (sum([p['score'] for p in data['gbp_grid']['grid']]) / 25.0) if data.get('gbp_grid') else "N/A",
                "fallout": len([p for p in data.get('gbp_grid', {}).get('grid', []) if p['score'] > 12]) if data.get('gbp_grid') else "N/A"
            }
        }

        prompt = f"""You are a GEO (Generative Engine Optimization) and SEO expert.
Based on the following audit status for "{status_summary['brand']}", generate a prioritized Optimization Roadmap.

STATUS SUMMARY:
{json.dumps(status_summary, indent=2)}

REQUIREMENTS:
1. THE TOP PRIORITY MUST BE GEO (AI Search visibility).
2. The second priority is Local SEO (Google Business Profile) and overall Brand Presence.
3. The third priority is technical and on-page SEO.

Structure the response as a JSON object with 3 categories of lists:
- 'quick_wins': Immediate actions (This Week)
- 'medium_term': Performance improvements (This Month)
- 'strategic': Long-term authority building (This Quarter)

Each item in the lists should be an object:
{{
  "action": "Clear actionable step",
  "category": "GEO" | "Local" | "SEO",
  "impact": "Brief impact statement"
}}
"""

        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"}
        )
        
        roadmap = json.loads(response.choices[0].message.content)
        return roadmap

    except Exception as e:
        print(f"Error generating roadmap: {e}")
        return {"quick_wins": [], "medium_term": [], "strategic": []}

def aggregate_data():
    data = {
        "url": "Unknown URL",
        "brand_name": "Unknown Brand",
        "geo_score": 0,
        "gbp": None,
        "scores": {
            "ai_citability": 0,
            "brand_authority": 0,
            "local_authority": 0,
            "content_eeat": 0,
            "technical": 0,
            "schema": 0,
            "platform_optimization": 0,
        },
        "findings": [],
        "crawlers": [],
        "platforms": {},
        "directories": None
    }

    fetch_data = {}
    if os.path.exists("test_fetch.json"):
        try:
            with open("test_fetch.json", "r") as f:
                fetch_data = json.load(f)
                data["url"] = fetch_data.get("url", data["url"])
                
                # Technical Score
                tech_score = 50
                if fetch_data.get("has_ssr_content"): tech_score += 30
                if fetch_data.get("status_code") == 200: tech_score += 20
                if len(fetch_data.get("errors", [])) > 0: tech_score -= 10
                
                # If page is completely blocked by bot protection (e.g. Amazon)
                if fetch_data.get("status_code") in [403, 202] or "robot" in fetch_data.get("text_content", "").lower():
                    data["findings"].append({
                        "severity": "critical", "title": "Anti-Bot Protection Detected",
                        "description": "The site blocked the analysis crawler. Scores will be artificially low."
                    })
                    tech_score = 10

                data["scores"]["technical"] = min(max(tech_score, 0), 100)

                # Schema Score
                schema_score = 10
                sd = fetch_data.get("structured_data", [])
                if sd:
                    schema_score = min(10 + (len(sd) * 20), 100)
                else:
                    data["findings"].append({
                        "severity": "high", "title": "No Schema Markup Detected",
                        "description": "Essential for AI entity resolution."
                    })
                data["scores"]["schema"] = schema_score

                # Content EEAT Score
                eeat_score = 30
                words = fetch_data.get("word_count", 0)
                if words > 500: eeat_score += 20
                if words > 1000: eeat_score += 20
                if fetch_data.get("title"): eeat_score += 15
                if fetch_data.get("heading_structure"): eeat_score += 15
                data["scores"]["content_eeat"] = min(eeat_score, 100)

        except Exception as e:
            print(f"Error reading test_fetch.json: {e}")

    # 1. Read Score Data
    if os.path.exists("test_citability.json"):
        try:
            with open("test_citability.json", "r") as f:
                score_data = json.load(f)
                data["url"] = score_data.get("url", data["url"])
                data["scores"]["ai_citability"] = score_data.get("average_citability_score", 0)
                if "findings" in score_data:
                    data["findings"].extend(score_data["findings"])
        except Exception as e:
            print(f"Error reading test_citability.json: {e}")

    # 2. Read Crawler / llms.txt Data
    if os.path.exists("test_llms.json"):
        try:
            with open("test_llms.json", "r") as f:
                crawler_json = json.load(f)

                # Pass the raw crawlers dict to the PDF generator
                if "crawlers" in crawler_json:
                    data["crawlers"] = crawler_json["crawlers"]

                    # Score based on real allow/block ratio
                    allowed = sum(1 for c in crawler_json["crawlers"].values() if c.get("status") == "Allowed")
                    blocked = sum(1 for c in crawler_json["crawlers"].values() if c.get("status") == "Blocked")
                    total = len(crawler_json["crawlers"])
                    if total > 0:
                        allow_ratio = allowed / total
                        plat_opt_score = int(allow_ratio * 60)  # up to 60 from crawler access
                    else:
                        plat_opt_score = 40

                    if blocked > 0:
                        data["findings"].append({
                            "severity": "high",
                            "title": f"{blocked} AI Crawlers Blocked",
                            "description": f"Your robots.txt is blocking {blocked} out of {total} AI crawlers, preventing citation."
                        })
                else:
                    plat_opt_score = 40

                # Bonus for llms.txt existence
                if crawler_json.get("exists", False):
                    plat_opt_score += 40
                else:
                    data["findings"].append({
                        "severity": "medium", "title": "Missing llms.txt",
                        "description": "No llms.txt file exists to guide AI systems to your best content."
                    })

                data["scores"]["platform_optimization"] = min(plat_opt_score, 100)
        except Exception as e:
            print(f"Error reading test_llms.json: {e}")


    # 3. Read Brand Data
    if os.path.exists("test_brand.json"):
        try:
            with open("test_brand.json", "r") as f:
                brand_data = json.load(f)
                data["brand_name"] = brand_data.get("brand_name", data["brand_name"])

                # Use the pre-calculated brand authority score if available
                if "brand_authority_score" in brand_data:
                    data["scores"]["brand_authority"] = int(brand_data["brand_authority_score"])

                if "platforms" in brand_data:
                    processed_platforms = {}
                    brand_auth_total = 0
                    brand_auth_count = 0
                    for key, info in brand_data["platforms"].items():
                        name = info.get("platform", key)

                        # New format: AI-generated numeric score directly
                        if "score" in info:
                            plat_score = int(info["score"])
                        else:
                            # Fallback: parse legacy "weight" string like "30%"
                            weight_str = info.get("weight", "0")
                            try:
                                plat_score = min(int(weight_str.replace('%', '').strip()) * 2, 100)
                            except ValueError:
                                plat_score = 0

                        processed_platforms[name] = plat_score
                        brand_auth_total += plat_score
                        brand_auth_count += 1

                    # Only fall back to average if brand_authority_score not already set
                    if data["scores"]["brand_authority"] == 0:
                        if brand_auth_count > 0:
                            data["scores"]["brand_authority"] = int(brand_auth_total / brand_auth_count)
                
                # Extract specific Local Directories data for the report
                if "Local Directories" in brand_data.get("platforms", {}):
                    data["directories"] = brand_data["platforms"]["Local Directories"]

        except Exception as e:
            print(f"Error reading test_brand.json: {e}")


    # 4. Read GBP Data
    if os.path.exists("test_gbp.json"):
        try:
            with open("test_gbp.json", "r") as f:
                gbp_data = json.load(f)
                data["gbp"] = gbp_data
                if "overall_local_score" in gbp_data:
                    data["scores"]["local_authority"] = int(gbp_data["overall_local_score"])
                
                if "findings" in gbp_data:
                    for f in gbp_data["findings"]:
                        # Tag as GBP finding
                        f["title"] = f"GBP: {f.get('title', 'Unknown')}"
                        data["findings"].append(f)
        except Exception as e:
            print(f"Error reading test_gbp.json: {e}")

    # 5. Read GBP Grid Data
    if os.path.exists("test_gbp_grid.json"):
        try:
            with open("test_gbp_grid.json", "r") as f:
                grid_data = json.load(f)
                data["gbp_grid"] = grid_data
        except Exception as e:
            print(f"Error reading test_gbp_grid.json: {e}")

    # 6. Read Simulation Engine Data
    if os.path.exists("test_sim.json"):
        try:
            with open("test_sim.json", "r") as f:
                sim_data = json.load(f)
                data["simulation"] = sim_data
        except Exception as e:
            print(f"Error reading test_sim.json: {e}")

    scores = data["scores"]
    total_score = sum(scores.values())
    if len(scores) > 0:
        data["geo_score"] = int(total_score / len(scores))
        
    # Calculate realistic AI Platform Readiness scores
    plat_opt = scores.get("platform_optimization", 0)
    cite = scores.get("ai_citability", 0)
    eeat = scores.get("content_eeat", 0)
    tech = scores.get("technical", 0)
    schema = scores.get("schema", 0)
    local = scores.get("local_authority", 0)
    brand = scores.get("brand_authority", 0)
    
    chatgpt = int(min(max((plat_opt * 0.5) + (cite * 0.4) + (tech * 0.1), 0), 100))
    perplexity = int(min(max((eeat * 0.4) + (cite * 0.4) + (tech * 0.2), 0), 100))
    sge = int(min(max((schema * 0.3) + (local * 0.4) + (eeat * 0.3), 0), 100))
    gemini = int(min(max((local * 0.4) + (cite * 0.3) + (tech * 0.3), 0), 100))
    bing = int(min(max((brand * 0.4) + (schema * 0.4) + (local * 0.2), 0), 100))

    data["platforms"] = {
        "Google AI Overviews": sge,
        "ChatGPT": chatgpt,
        "Perplexity": perplexity,
        "Gemini": gemini,
        "Bing Copilot": bing
    }
    
    # Enrich findings with AI for more detail and examples
    data["findings"] = enrich_findings_with_ai(data["findings"], data["brand_name"], data["url"])

    # Phase 9: Generate dynamic Optimization Roadmap
    roadmap = generate_optimization_roadmap(data)
    data["quick_wins"] = roadmap.get("quick_wins", [])
    data["medium_term"] = roadmap.get("medium_term", [])
    data["strategic"] = roadmap.get("strategic", [])

    return data

if __name__ == "__main__":
    aggregated_data = aggregate_data()
    
    # If no data found, warn and exit
    if aggregated_data["url"] == "Unknown URL" and aggregated_data["geo_score"] == 0:
        print("Warning: No intermediate audit files found. Make sure to run the other steps first.")
        print("Generating a fallback report with missing data...")
        
    output_filename = "ORBIS-LOCAL-LIVE-REPORT.pdf"
    
    print(f"Aggregated live data for {aggregated_data['url']}")
    print("Generating PDF...")
    
    generate_report(aggregated_data, output_path=output_filename)
    print(f"Successfully generated {output_filename}")
